<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $model app\models\NoIzinDokter */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="no-izin-dokter-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'no_izin')->textInput(['maxlength' => true]) ?>
     <?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
            $form->field($model, 'keahlian')->widget(\kartik\select2\Select2::className(), [
                'data' => ArrayHelper::map(backend\models\Spesialis\Spesialis::find()->all(), 'id', 'spesialis'),
                'options' => [
                    'prompt' => 'Pilih Jenis Keahlian'
                ],
            ])->label('Jenis Keahlian'); ?>



    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>
